### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by GongJS** [algorithm010/algorithm010#19]
#学号:G20200343070204
#姓名:橙澈
#班级:2班
#小组:3组
#作业&总结链接:https://github.com/GongJS/algorithm010/tree/master/Week01

**Comment by yuelog** [comment]
#学号:G20200343070168
#姓名:赖鸿钺
#班级:2班
#小组:6组
#作业&总结链接:
https://github.com/yuelog/algorithm010/tree/master/Week01
