### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by xiaoxiaozhao** [algorithm010/algorithm010#20]
#学号:G20200343070009
#姓名:小赵
#班级:1班
#小组:10组
#作业&总结链接:https://github.com/xiaoxiaozhao/algorithm010/tree/master/Week01

**Comment by lanweiyt** [comment]
#学号:G20200343070290
#姓名:兰威
#班级:2班
#小组:10组
#编程语言：Java
#作业&总结链接:https://github.com/lanweiyt/algorithm010/tree/master/Week01
