### ISSUE TITLE
第一周作业提交

### ISSUE THREAD

**Issue by wuwenrui** [algorithm010/algorithm010#28]
#学号: G20200343070299
#姓名:武文瑞
#班级:1班
#小组:10组
#语言:Java
#作业&总结链接:https://github.com/wuwenrui/algorithm010/tree/master/Week01

**Comment by Deamon-wang** [comment]
https://github.com/Deamon-wang/algorithm010/tree/master/Week01
#学号: G20200343070224
#姓名:王伟
#班级:2班
#小组:
#语言:python
#作业&总结链接:https://github.com/Deamon-wang/algorithm010/tree/master/Week01

**Comment by hutongxuehyz** [comment]
#学号:G20200343070124
#姓名:胡亚洲
#班级:2班
#小组:2组
#作业&总结链接:https://github.com/hutongxuehyz/algorithm010/commit/8308d6515c27246d5674e842e4f9a08d2f25006c

**Comment by zbygo** [comment]
#学号: G20200343070163
#姓名:赵柏杨
#班级:1班
#小组:2组
#语言:Java
#作业&总结链接:https://github.com/zbygo/algorithm010/tree/master/Week01
